metainfo :
    author: Thomas Baldauf, German Aerospace Center (DLR)
    date: November 2021
    info: Example project

params:
    - name: Cash
      depreciation: 0.0
      price: p
      value: 1.0
      unit: Euro
      description: my numeraire, the only

    - name: Bonds
      depreciation: 0.0
      price: p_G
      value: 1.0
      unit: Euro
      description: government bonds

hyperparams:
    - name: T
      value: 500
      description: number of simulation steps
    
    - name: T_burn
      value: 400
      description: number of burn-in simulation steps

    - name: theta
      value: 0.125
      description: fixed tax rate (percent of gdp)

    - name: alpha1
      value: 0.8
      description: share of income on consumption

    - name: alpha2
      value: 0.51
      description: share of wealth on consumption

    - name: G
      value: 0.442
      description: fixed government expenditures (percent of gdp)

    - name: gdp_change
      value: "data/processed/tipsau20_gdp_processed.txt"
      description: empirical percentage change of GDP